package classifier

// intentExamples maps each intent class to its handwritten seed queries.
// These are embedded at startup and averaged into one prototype vector per class.
// Chosen to be clearly representative with no cross-class ambiguity.
// Replace with real query samples from traffic once enough data accumulates.
var intentExamples = map[string][]string{
	"news": {
		"kenya election results today",
		"breaking news nairobi",
		"premier league scores this weekend",
		"latest developments ukraine conflict",
		"what happened in parliament yesterday",
		"stock market close today",
		"new product launch apple",
		"government budget announcement",
		"africa cup of nations results",
		"weather forecast nairobi tomorrow",
		"latest headlines technology",
		"political developments this week",
		"sports results today",
		"breaking economic news",
		"current events africa",
	},
	"factual": {
		"capital of france",
		"when was redis created",
		"what is the speed of light",
		"population of nairobi",
		"who invented the telephone",
		"height of mount kenya",
		"what year did golang release",
		"distance nairobi to mombasa",
		"boiling point of water",
		"how many bytes in a megabyte",
		"what language is spoken in brazil",
		"age of the universe",
		"who is the president of kenya",
		"when did world war two end",
		"what is the capital of japan",
	},
	"code": {
		"how to handle goroutine panic in go",
		"python list comprehension syntax",
		"rust lifetime error how to fix",
		"javascript async await example",
		"sql join types explained",
		"docker compose volumes tutorial",
		"git rebase vs merge difference",
		"regex match email address pattern",
		"http status codes reference",
		"postgres index types explained",
		"how to implement a binary search tree",
		"golang channels tutorial",
		"react useEffect hook example",
		"kubernetes deployment yaml example",
		"how to write unit tests in go",
	},
	"research": {
		"summary of designing data intensive applications chapter 3",
		"overview of transformer architecture in machine learning",
		"comparison of consensus algorithms raft vs paxos",
		"how does the linux kernel scheduler work",
		"explain the cap theorem in distributed systems",
		"history of the internet protocols",
		"tradeoffs of event sourcing architecture",
		"deep dive into go garbage collector",
		"explain bitcoin proof of work mechanism",
		"overview of vector databases and use cases",
		"analysis of microservices vs monolith tradeoffs",
		"how does tls handshake work in detail",
		"research on large language model training",
		"distributed systems consistency models explained",
		"in depth guide to database indexing strategies",
	},
	"commercial": {
		"best laptop under 1000 dollars",
		"iphone versus samsung comparison",
		"cheapest flight nairobi to london",
		"recommended mechanical keyboard for programming",
		"macbook pro review",
		"which cloud provider is cheapest for kubernetes",
		"best noise cancelling headphones",
		"standing desk recommendations",
		"budget gaming monitor under 300",
		"best vpn service this year",
		"top rated wireless earbuds",
		"affordable ergonomic office chair",
		"best smartphone camera comparison",
		"recommended project management software",
		"top rated antivirus software",
	},
	"general": {
		"how to make tea",
		"tips for better sleep",
		"what to do in nairobi this weekend",
		"how to negotiate a salary",
		"good books to read this year",
		"home workout routine no equipment",
		"how to learn a new language fast",
		"productivity tips for remote work",
		"how to start a podcast",
		"basic car maintenance checklist",
		"healthy meal prep ideas",
		"how to improve public speaking",
		"tips for managing personal finances",
		"how to grow tomatoes at home",
		"best practices for time management",
	},
}